(function(){"use strict";
const page=document.querySelector("#birthdayPage"),slug=new URLSearchParams(location.search).get("slug");
const layouts={T01:["55%","3%","39%","28%","28%","35%","18%","40%","64%"],T02:["53%","4%","41%","29%","29%","34%","15%","40%","70%"],T03:["55%","4%","39%","31%","30%","37%","12%","41%","58%"],T04:["17%","7%","66%","21%","74%","35%","16%","43%","68%"],T05:["16%","4%","69%","37%","56%","43%","13%","53%","74%"],T06:["17%","6%","67%","28%","71%","42%","17%","51%","66%"],T07:["31%","3%","47%","24%","48%","34%","21%","42%","57%"],T08:["9%","5%","82%","24%","61%","31%","24%","43%","64%"],T09:["43%","6%","41%","32%","26%","25%","18%","48%","68%"],T10:["8%","2%","84%","41%","66%","36%","24%","48%","55%"],T11:["8%","5%","84%","20%","58%","30%","17%","43%","67%"]};
const palettes={T01:["#ef5480","#3e95e9","#fffdf8"],T02:["#d84d35","#185a8d","#fff0d0"],T03:["#e26158","#3190d5","#fff5df"],T04:["#e261ac","#f4ca57","#0c4590"],T05:["#ed6990","#b37bf0","#fff9f7"],T06:["#e36d8d","#d9b2c2","#171217"],T07:["#e97f5a","#75a197","#fff2dd"],T08:["#cb8092","#b196d2","#fff3f6"],T09:["#2b78c4","#85b9d6","#eef8ff"],T10:["#f45089","#f0ba18","#fff4fa"],T11:["#ed2875","#276ce7","#fff9ed"]};
if(!slug||!/^[a-zA-Z0-9_-]{12,64}$/.test(slug)){error("这份生日惊喜链接无效或已失效。");return}load();
async function load(){try{const c=window.BirthdaySupabase&&window.BirthdaySupabase.getClient();if(!c)throw Error("生日页服务暂未配置。");const {data,error:e}=await c.functions.invoke("get-published-page",{body:{slug}});if(e)throw e;if(!data?.page)throw Error(data?.error||"未找到这份生日惊喜。");render(data.page)}catch(e){console.error(e);error(e.message||"这份生日惊喜暂时无法打开。")}}
function render(x){const id=x.templateId||"T01",l=layouts[id]||layouts.T01,p=x.palette||{},f=palettes[id]||palettes.T01,primary=p.primary||p.primaryColor||f[0],accent=p.accent||p.accentColor||f[1],bg=p.background||p.backgroundColor||f[2],r=x.recipient||{},ct=x.content||{},ph=x.photos||{},cover=ph.cover?.url||"assets/templates/"+id+"/preview.png",gallery=Array.isArray(ph.gallery)?ph.gallery:[],s=x.modules?.surpriseBox?.enabled?x.modules.surpriseBox:null;
document.title=(r.name||"生日")+"的生日惊喜";document.documentElement.style.setProperty("--page-bg",bg);document.documentElement.style.setProperty("--page-primary",primary);document.documentElement.style.setProperty("--page-accent",accent);
page.innerHTML=`<div class="template-shell template-${a(id)}"><div class="template-board" style="--cx:${l[0]};--cy:${l[1]};--cw:${l[2]};--ch:${l[3]};--nx:${l[4]};--ny:${l[5]};--tx:${l[6]};--ty:${l[7]};--tw:${l[8]}"><img class="template-art" src="assets/templates/${a(id)}/preview.png" alt="" aria-hidden="true"><div class="template-photo"><img src="${a(cover)}" alt="${a(r.name||"生日封面")}" referrerpolicy="no-referrer"></div><strong class="template-name">${h(r.name||"TA")}</strong><div class="template-count" id="birthdayCountdown"></div></div><section class="personal-note"><p class="note-kicker">For ${h(r.name||"you")}</p><h1>${h(ct.headline||"把今天所有的偏爱和祝福，都送给你")}</h1><p>${h(ct.message||"愿你被爱包围，也被快乐稳稳接住。")}</p>${ct.signature?`<small>${h(ct.signature)}</small>`:""}</section>${s?`<section class="template-module surprise-card"><p class="note-kicker">一份专属惊喜</p><h2>${h(s.surpriseTitle||"给你藏了一份小惊喜")}</h2><p>打开后，让这套生日模板短暂进入专属沉浸场景。</p><button class="primary-action" id="openSurprise">打开惊喜盲盒</button></section>`:""}${gallery.length?`<section class="template-module"><p class="note-kicker">Memory Album</p><h2>回忆相册</h2><div class="gallery">${gallery.map(q=>`<figure><img src="${a(q.url)}" alt="${a(q.caption||"回忆照片")}" loading="lazy" referrerpolicy="no-referrer"></figure>`).join("")}</div></section>`:""}<footer class="page-footer">本页使用 ${h(x.templateName||id)} 模板制作<br>仅通过专属链接访问</footer></div>`;
tick(r.birthday);setInterval(()=>tick(r.birthday),1000);document.querySelector("#openSurprise")?.addEventListener("click",()=>window.openSurpriseExperience?.(s,{templateId:id,primaryColor:primary,accentColor:accent,backgroundColor:bg}))}
function tick(v){const o=document.querySelector("#birthdayCountdown"),d=next(v);if(!o||!d)return;const n=Math.max(0,d-Date.now()),u=[[Math.floor(n/86400000),"天"],[Math.floor(n%86400000/3600000),"时"],[Math.floor(n%3600000/60000),"分"],[Math.floor(n%60000/1000),"秒"]];o.innerHTML=u.map(([x,y])=>`<div><strong>${String(x).padStart(2,"0")}</strong><span>${y}</span></div>`).join("")}
function next(v){const d=new Date(v+"T00:00:00");if(!v||isNaN(d))return null;const n=new Date();let t=new Date(n.getFullYear(),d.getMonth(),d.getDate());if(t<n)t=new Date(n.getFullYear()+1,d.getMonth(),d.getDate());return t}
function error(m){page.innerHTML=`<section class="birthday-error"><strong>暂时无法打开</strong><p>${h(m)}</p></section>`}
function h(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function a(v){return h(v)}
})();